# Generated by Django 2.2.2 on 2019-07-01 23:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örnek:  Doğalgaz (Kombi)', max_length=255, verbose_name='Tip')),
            ],
            options={
                'verbose_name': 'Isıtma Tipi',
                'verbose_name_plural': 'Isıtma Tipleri',
            },
        ),
        migrations.CreateModel(
            name='PropertTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='örnek: Cephe, Ulaşım', max_length=255, verbose_name='Başlık')),
            ],
            options={
                'verbose_name': 'Özellik Başlığı',
                'verbose_name_plural': 'Özellik Başlıkları',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Özellik')),
            ],
            options={
                'verbose_name': 'Özellik',
                'verbose_name_plural': 'Özellikler',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='örnek 1+1, 2+1', max_length=10, verbose_name='Oda tipi')),
            ],
            options={
                'verbose_name': 'Oda',
                'verbose_name_plural': 'Oda',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tip',
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='apartment_age',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Apartman Yaşı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='bathroom_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Banyo Sayısı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='content',
            field=models.TextField(default=' ', verbose_name='Açıklama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='coordinates',
            field=models.CharField(default=' ', help_text='örnek: 56.545454, 59.32454', max_length=25, verbose_name='Konum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='dues',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Aidat'),
        ),
        migrations.AddField(
            model_name='advert',
            name='in_site',
            field=models.BooleanField(default=True, verbose_name='Site İçerisinde'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='is_furniture',
            field=models.BooleanField(default=True, verbose_name='Eşyalı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='price',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ücret'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 23, 32, 13, 46498, tzinfo=utc), verbose_name='Yayınlanma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='quarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='adverts', to='address.Quarter', verbose_name='mahalle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='square',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='m² (Brüt)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='square_useful',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='m² (Net)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='status',
            field=models.CharField(default=1, max_length=255, verbose_name='Kullanım Durumu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='title',
            field=models.CharField(default=' ', max_length=255, verbose_name='Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='heating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='adverts', to='advert.HeatType', verbose_name='Isınma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='properties',
            field=models.ManyToManyField(related_name='adverts', to='advert.Property', verbose_name='Özellikleri'),
        ),
        migrations.AddField(
            model_name='advert',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='adverts', to='advert.Room', verbose_name='Oda Sayısı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='adverts', to='advert.Type', verbose_name='Tipi'),
            preserve_default=False,
        ),
    ]
