# Generated by Django 2.2.2 on 2019-06-30 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fade_duration', models.PositiveSmallIntegerField(verbose_name='Karartma Süresi(sn)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panorama',
                'verbose_name_plural': 'Panoramas',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Screen ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('hfov', models.FloatField(verbose_name='hfov')),
                ('pitch', models.FloatField(verbose_name='pitch')),
                ('yaw', models.FloatField(verbose_name='yaw')),
                ('northOffset', models.PositiveSmallIntegerField(verbose_name='northOffset')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order')),
                ('image', models.ImageField(upload_to='panorama-screens/')),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='screen.Panorama')),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('url', models.URLField(blank=True, null=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='screen.Screen')),
            ],
            options={
                'verbose_name': 'HotSpot',
                'verbose_name_plural': 'HotSpots',
            },
        ),
    ]
