# Generated by Django 2.2.2 on 2019-06-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='panorama',
        ),
        migrations.AddField(
            model_name='screen',
            name='advert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='advert.Advert'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Panorama',
        ),
    ]
