# Generated by Django 2.2.2 on 2019-07-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_auto_20190701_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='hfov',
            field=models.FloatField(blank=True, null=True, verbose_name='hfov'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Screen ID'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='northOffset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='northOffset'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='pitch',
            field=models.FloatField(blank=True, null=True, verbose_name='pitch'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='yaw',
            field=models.FloatField(blank=True, null=True, verbose_name='yaw'),
        ),
    ]
