# Generated by Django 2.2.2 on 2019-07-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0004_auto_20190703_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='type',
            field=models.CharField(blank=True, choices=[('info', 'info'), ('scene', 'scene')], max_length=5, null=True, verbose_name='Types'),
        ),
    ]
