# Generated by Django 2.2.2 on 2019-07-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0005_auto_20190704_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspot',
            old_name='screenid',
            new_name='screenId',
        ),
    ]
