# Generated by Django 2.2.2 on 2019-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0006_auto_20190704_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='pitch',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='yaw',
            field=models.SmallIntegerField(),
        ),
    ]
