# Generated by Django 2.2.2 on 2019-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0007_auto_20190704_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='pitch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='yaw',
            field=models.IntegerField(),
        ),
    ]
