# Generated by Django 2.2.2 on 2019-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0008_auto_20190704_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='pitch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='yaw',
            field=models.CharField(max_length=100),
        ),
    ]
