# Generated by Django 2.2.2 on 2019-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0009_auto_20190704_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='pitch',
            field=models.CharField(max_length=255, verbose_name='pitch'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='yaw',
            field=models.CharField(max_length=255, verbose_name='yaw'),
        ),
    ]
