# Generated by Django 2.2.2 on 2019-07-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0010_auto_20190704_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='hfov',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hfov'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='pitch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='pitch'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='yaw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='yaw'),
        ),
    ]
